[workspace]
members = ["crates/*"]
resolver = "2"

[package]
name = "cppvtable-examples"
version = "0.1.0"
edition = "2024"
description = "Examples and tests for cppvtable"

[dependencies]
cppvtable = { path = "crates/cppvtable" }
cpp = "0.5"

[build-dependencies]
cpp_build = "0.5"
