[workspace]
members = ["crates/*"]
resolver = "2"

[package]
name = "vtables"
version = "0.1.0"
edition = "2024"

[dependencies]
vtable = { path = "crates/vtable" }
cpp = "0.5"

[build-dependencies]
cpp_build = "0.5"
